# Generated by Django 6.0.3 on 2026-04-12 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='recruiter_name',
            new_name='receiver_name',
        ),
    ]
