# Generated by Django 6.0.3 on 2026-04-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_rename_recruiter_name_parcel_receiver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
