# Generated by Django 6.0.3 on 2026-04-15 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
        ('parcels', '0003_parcel_pickup_lat_parcel_pickup_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='assigned_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='couriers.courierprofile'),
        ),
    ]
